### ISSUE TITLE
CSS missing?

### ISSUE THREAD

**Issue by jxxcarlson** [HubPress/hubpress.io#173] opened 2015-04-03 12:49 UTC
The centered, blue text provided by

```
[.text-center]
[blue]#_Write once, publish many._#
```

is visible in editor preview but not in the rendered blog.  I am using the Roon theme.  (PS HubPress is great!)

**Comment by lametaweb** [comment] 2015-05-03 18:37
Hi again^2. You can look at this [PR](https://github.com/HubPress/hubpress.io/pull/198). It would resolve the same problem on ichi theme. Go to the two last commits. You will have to do it manually ultil it's resolved in a new release. Cheers.

**Comment by jxxcarlson** [comment] 2015-05-03 19:09
Thankyou !!

**Comment by jaredmorgs** [comment] 2016-10-05 10:58
This issue is pretty old now. Does the issue present still @jxxcarlson ? would you mind closing it off if you believe the issue is fixed. Sorry for taking so long to catch up on all the open bugs.

**Closed** 2017-03-09 11:54 UTC
Labels: bug
