### ISSUE TITLE
Can't log in on Administrator page

### ISSUE THREAD

**Issue by feskyde** [HubPress/hubpress.io#300] opened 2015-11-12 02:14 UTC
I entered to the /hubpress [log in page](http://feskyde.github.io/hubpress/#/login) and putted my username and password, but it get a error :disappointed:

**Comment by raisedadead** [comment] 2015-11-16 12:55
Hi @feskyde ,
Can you please elaborate the steps? Add a few screenshots? Or point to repo where you have been facing the issue.

The community will be glad to help, just let us know the specifics of the issue that you are facing.

regards,
raisedadead

**Comment by matsp** [comment] 2015-11-17 19:10
It's the same for me. 
After doing the installation steps I can't login with my github credentials.

**Comment by anthonny** [comment] 2015-11-17 21:03
@matsp you can't use the gh-pages branch with  a repo named matsp.github.io. You must use the master branch, it is a GitHub convention

**Comment by matsp** [comment] 2015-11-18 07:27
Thanks for your tip! I'm not very familiar with this feature yet.

**Comment by rickpowellauthor** [comment] 2015-12-11 19:14
I'm having the same probem and I'm on the master branch. Could you take a look: https://github.com/rickpowellauthor/rickpowellauthor.github.io.

**Comment by anthonny** [comment] 2015-12-11 20:49
@rickpowellauthor you made a mistake in your config.json file. You must keep the keys repositoryName and username and put the corresponding values at the right place. You can have a look at the @demo-hubpress repo

**Comment by rickpowellauthor** [comment] 2015-12-11 21:41
@anthonny It helps if I put the information in the right place. :smile: Thanks of the help.

**Comment by kskarthik** [comment] 2016-02-26 11:46
@anthonny I faced the same issue now

Just followed the steps for setting up the blog & went to the address http://hubpress.github.io/demo.hubpress.io/hubpress to login

# What happened
* First login was successful
* Right from the 2nd login the page is just not redirecting to the editor but stuck right there but showing successful authentication message.

I am using firefox 43 browser on linux

**Comment by raisedadead** [comment] 2016-02-26 15:20
@kskarthik Do you mean that you were trying to login on `https://kskarthik.github.io/hubpress` and not `http://hubpress.github.io/demo.hubpress.io/hubpress` 

The former is your repo and later is hubpress's , on which of course you dont have login rights.

Please correct me if you were trying to do something different?

**Comment by anthonny** [comment] 2016-02-26 15:35
We had a chat on https://hubpressio-slack.herokuapp.com/

We solved the problem, see https://github.com/HubPress/hubpress.io/issues/333
I close the issues, the problem is solve for everyone :smile:

**Comment by anthonny** [comment] 2016-02-26 15:36
@raisedadead Thank you for your comment ;)

**Closed by anthonny** 2016-02-26 15:35 UTC

**Comment by raisedadead** [comment] 2016-02-26 15:42
Ahh cool! :wink:
