### ISSUE TITLE
Hubpress sitemap

### ISSUE THREAD

**Issue by greatwarlive** [HubPress/hubpress.io#493] opened 2017-03-07 23:37 UTC
I think hubpress should have a sitemap to help goggle understand our blogs better - is that possible?

**Comment by anthonny** [comment] 2017-03-08 00:10
Hi @greatwarlive! Thank you for your interest about HubPress.

I agree, and yes it is possible to implement. I will try to plan this change asap

I close this issue because it is a duplicate of https://github.com/HubPress/hubpress.io/issues/72

**Closed by anthonny** 2017-03-08 00:10 UTC
Labels: duplicate
