### ISSUE TITLE
[Enhancement] Enable Code Highlighter for Posts

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/hubpress.io#94] opened 2015-02-17 01:10 UTC
I'm a tech blogger and find myself writing many command-line examples in the blog posts I write. 

For example, http://jaredmorgs.github.io/2015/02/16/Build-API-Docs-for-the-RHQ-Project.html is full of code samples, but there is very little syntax highlighting on them.

Perhaps HubPress hasn't yet included a code highlighter library in the app. Or perhaps it is down to the theme applied.

The code block below shows the source-highlighter declared inside a post, with all the supported AsciiDoctor options.

```
= Build API Docs for the RHQ Project 
:hp-tags: Maven, RHQ, API Docs
:hp-image: http://github.com/jaredmorgs/jaredmorgs.github.io/images/covers/open_source.jpg
:published_at: 2015-02-16
:source-highlighter: pygments|coderay|hightlightjs|prettify
```

How AsciiDoctor supports code highlighting is described here: http://asciidoctor.org/docs/asciidoc-asciidoctor-diffs/#source-code-highlighting

How you declare syntax highlighting in a post is described here: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code

What would be awesome is if this was appended as an addition to the Settings configuration of HubPress, so you could seamlessly apply the code highlighting across all posts, rather than separately in each post like I've done above.

**Comment by anthonny** [comment] 2015-02-17 07:11
:+1: 

I thought of adding `highlight.js` as an option in the Settings. In the option is checked, then i'll add the attribute `:source-highlighter: hightlightjs` when i call `Asciidoctor.convert`

**Comment by jaredmorgs** [comment] 2015-02-17 09:30
Sounds great, mate. And then I can doc that highlight.js is the
highlighter.

**Comment by ArgTang** [comment] 2015-03-12 09:18
dont know how far you have come with this. i just wanted to add support for this as a feature.

alo an alternative to hihglight.js is http://prismjs.com dont know witch would be easier to implement though

**Comment by anthonny** [comment] 2015-03-14 23:27
@ArgTang thanks for your comment but the work is done now.

@jaredmorgs, if it's good for you, you can close the issue

**Comment by anthonny** [comment] 2015-03-20 09:10
Feel free to reopen if necessary

**Closed by anthonny** 2015-03-20 09:10 UTC
Labels: enhancement, should be fixed

**Comment by OlgaMaciaszek** [comment] 2015-06-05 19:37
@anthonny where can this option be found? I have recently forked the project and built the blog site, but I don't see it on the settings site; or shall I just add this manually in the code? if yes, where?

**Comment by jaredmorgs** [comment] 2015-06-05 22:13
Have you marked up your blog post code using the suggested syntax markup in
the Asciidoctor User Guide?

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code

If you declare the type of code you're writing, the highlighter will pick
that up and colorize your code accordingly.

On Sat, Jun 6, 2015, 05:37 Olga Maciaszek-Sharma <notifications@github.com>
wrote:

> @anthonny <https://github.com/anthonny> where can this option be found? I
> have recently forked the project and built the blog site, but I don't see
> it on the settings site; or shall I just add this manually in the code? if
> yes, where?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HubPress/hubpress.io/issues/94#issuecomment-109415696>
> .
>
-- 

Sent from Mobile.

**Comment by OlgaMaciaszek** [comment] 2015-06-06 10:39
Yes, I have.

Ok. It  works. The issue is that the highlight is not visible in the preview, so that's why I thought it didn't work.

However, it works fine on the final display.
