### ISSUE TITLE
Error when creating a new post 

### ISSUE THREAD

**Issue by tonyynot** [HubPress/hubpress.io#61] opened 2015-02-11 21:08 UTC
Remote save
An error has occurred, see your console for more informations.

Same error occurs when I click the console icon.

**Comment by anthonny** [comment] 2015-02-11 21:13
Hi @tonyynot !
Can you rename your repository to tonyynot.github.io and update the repositoryName in your config.json ?
Then open http://tonyynot.github.io/hubpress , login and try to save.

**Comment by tonyynot** [comment] 2015-02-11 21:41
I did that and now I am receiving an authentication error at login attempt.

**Comment by anthonny** [comment] 2015-02-11 21:44
You did not update the repositoryName in your config.json

**Comment by tonyynot** [comment] 2015-02-11 22:04
config.json updated to my user. login successful, same "remote save" error when making a post.

**Comment by anthonny** [comment] 2015-02-11 22:07
can you show me the content you try to save ?

**Comment by tonyynot** [comment] 2015-02-11 22:11
![screen shot 2015-02-11 at 5 10 54 pm](https://cloud.githubusercontent.com/assets/9784303/6157636/f639ca0c-b210-11e4-8dc7-1efa2002d800.png)

**Comment by anthonny** [comment] 2015-02-11 22:16
The minimum requirement is a title (recently added in the doc), try with : 

```
= My title

Lorem ipsum ......
```

**Comment by anthonny** [comment] 2015-02-11 22:43
It seems to be ok ?

**Comment by tonyynot** [comment] 2015-02-11 23:39
Yes the posting works now but I can't get the posts to show on the page

**Comment by anthonny** [comment] 2015-02-11 23:42
Your post is not published, did you try to publish it (button on the right of the save button) ?

**Comment by codinfox** [comment] 2015-02-12 15:01
same issue here

**Comment by tonyynot** [comment] 2015-02-12 18:18
I got several notifications that my post had been published and it still would not display.

**Comment by anthonny** [comment] 2015-02-12 18:23
@tonyynot I can find your repository ? Is it a private one ? if yes, can you give me the right to access ?
@codinfox same, i can't see your repository

**Comment by codinfox** [comment] 2015-02-13 02:56
@anthonny I have added you to my collaborators. The repo is [here](https://github.com/codinfox/blog-new). It's weird that the post used to be unable to publish but it got published just now. Should it be displayed automatically on the homepage or are some extra configurations needed?  By the way, the app.js is way too large and is kinda difficult to let others contribute.

**Comment by anthonny** [comment] 2015-02-13 09:17
@codinfox glad to see your post now. There isn't extra configurations needed. It should be automatically displayed on your home page, but sometimes there is some latencies.

**Comment by codinfox** [comment] 2015-02-13 17:03
@anthonny I found the post. Thanks!

**Comment by nuklea** [comment] 2015-02-16 06:07
Same issue.

**Comment by anthonny** [comment] 2015-02-17 08:13
Hi @nuklea !
I'm sorry i was so long to answer, you config seems to be ok, can you show me the content you try to save ?

**Comment by nuklea** [comment] 2015-02-18 04:00
Any content. For example:

```
== hello, world

My first post.
```

17.02.2015 15:13, Anthonny Quérouil пишет:

**Comment by anthonny** [comment] 2015-02-18 06:29
```
== hello, world

My first post.
```

This content is not good, you must have a first level header, this should work : 
```
= My title

== hello, world

My first post.
```

**Comment by jaredmorgs** [comment] 2015-02-19 04:04
Waiting for @nuklea to confirm it was an AsciiDoc syntax error, then close issue.

**Comment by nuklea** [comment] 2015-02-19 04:28
@jaredmorgs confirmed. @anthonny thanks.

**Comment by jaredmorgs** [comment] 2015-02-19 04:46
Closing

**Closed by jaredmorgs** 2015-02-19 04:46 UTC
Labels: wontfix
