### ISSUE TITLE
Index page shows only the last published post

### ISSUE THREAD

**Issue by lai** [HubPress/hubpress.io#31] opened 2015-02-09 22:15 UTC
Every time I published a new post, the index page gets overwritten showing just the latest post. I've set the Posts per page in the settings to be more than 1.

**Comment by anthonny** [comment] 2015-02-09 22:28
Hi @lai,

I can't find your repository, maybe that you deleted it ?

**Comment by lai** [comment] 2015-02-10 00:21
@anthonny thanks for the prompt reply. I did my setup on Github Enterprise and with few minor tweaking everything seems working. One problem is that index page only shows one post. Another issue is that when I changed the theme setting, the index page will show none of the posts I added. So far I haven't seen on the demo site you've created more than one post. Would it be easy for you to try and repro this? Thanks!

**Comment by jericksanjuan** [comment] 2015-02-10 03:26
I can confirm the 2 issues described here (theme change showing no posts, only last published shown) as it also occured on my fork.

**Comment by anthonny** [comment] 2015-02-10 06:34
@jericksanjuan I look at your repo, all seems to be good except pagination in your config.json. 
In the settings screen, can you set the pagination to 10 ?

@lai same for you can you try to force the pagination please ?

**Comment by anthonny** [comment] 2015-02-10 08:22
seems to be good for you @jericksanjuan

**Comment by yassineS** [comment] 2015-02-10 16:16
Hi @anthonny I am facing the same issue, I set pagination to a number > 1 however it does shows only the last posted post.

**Comment by Bloggerschmidt** [comment] 2015-02-11 07:37
Same issue here. Change it to "postsPerPage":"10" in config.json with no effect. Only one post display @ http://bloggerschmidt.github.io/ 

config.json
https://github.com/Bloggerschmidt/Bloggerschmidt.github.io/blob/master/hubpress/config.json

**Comment by anthonny** [comment] 2015-02-11 07:57
Hi @yassineS, @Bloggerschmidt ,

Your posts are correctly published (in the list posts, each post should have the left border in green).
Please, can you go in the settings page, and just submit the form? Wait for the second alert, and then refresh your blog (when you save the settings, each published post is rebuild).

There is certainly a bug with the pagination, it could complicated to described but i need a more "step by step" explanation to try to reproduce and analyze.

**Comment by Bloggerschmidt** [comment] 2015-02-11 08:13
First: Thank you very much for your work and support. I do as you has decribed and all post were unbublished. So I create two new posts with the same effect above. Strange: Each (published) post has the left border in orange. Maybe I should fork it again.

**Comment by anthonny** [comment] 2015-02-11 08:28
Which browser do you use ?

**Comment by Bloggerschmidt** [comment] 2015-02-11 08:30
Firefox Developer

**Comment by Bloggerschmidt** [comment] 2015-02-11 08:31
Ah, in Chrome it is green.

**Comment by anthonny** [comment] 2015-02-11 08:32
can you try to publish in chrome please ?

**Comment by Bloggerschmidt** [comment] 2015-02-11 08:33
Cool. When I save settings via chrome everthing works fine. Thank youl.

**Comment by anthonny** [comment] 2015-02-11 08:34
@Bloggerschmidt  Thank you so much ! Thanks to you, I know that there is a problem with Firefox

**Comment by yassineS** [comment] 2015-02-11 23:16
@anthonny The issue still persist, I resubmitted the settings form and the two notifications showed up. But on the posts list, I see 3 posts, however there's only 2 of them that are in the _posts directory, and none of the two that I saved and published many times show up on the feed!

**Comment by anthonny** [comment] 2015-02-11 23:37
@yassineS I just sent you an invite on gitter

**Comment by anthonny** [comment] 2015-02-12 00:23
@lai , @jericksanjuan , is it ok for you ?

**Comment by lai** [comment] 2015-02-12 00:39
what would you want me to do? @anthonny 

I was using Chrome and it didn't work for me.

**Comment by anthonny** [comment] 2015-02-12 00:43
@lai > https://github.com/HubPress/hubpress.io/issues/31#issuecomment-73651555

**Comment by lai** [comment] 2015-02-12 19:27
@anthonny I fetched the latest changes and it's still not working.

**Comment by anthonny** [comment] 2015-02-12 19:43
@lai can you give me the right to write in your repo ?

**Comment by lai** [comment] 2015-02-12 21:08
hey @anthonny, I don't understand how just looking at my repo would solve this issue. The same way I don't understand how trying out different browsers would make a difference in this case. Do you need more info to verify this?

I was going to see if I can fix this myself. As far as I can tell, only the compiled javascript code is in this repo and the original source written in React.js is not checked in here. Do you intended to make the source available?

**Comment by anthonny** [comment] 2015-02-12 21:24
> I don't understand how just looking at my repo would solve this issue

Looking at your browser will not solve the problem but i'll certainly help me to understand what happen.

> The same way I don't understand how trying out different browsers would make a difference in this case

Try another browser was for @Bloggerschmidt because HubPress not deal very with indexedDb on FireFox that's why i recommend using Chrome during the preview.

> Do you intend to make the source available?

Yes there is an issue for that, certainly at the end of the month

**Comment by anthonny** [comment] 2015-02-25 16:05
@Bloggerschmidt firefox should work now if you merge the upstream ;)
There's still a bug with **Firefox developer edition** if you use **https**

@lai can i close this issue?

**Comment by Bloggerschmidt** [comment] 2015-02-26 10:27
awesome! Awesome! AWESOME! Works on Firefox like a charm.

**Comment by anthonny** [comment] 2015-02-26 10:30
@Bloggerschmidt :beers:

**Comment by lai** [comment] 2015-02-26 20:15
@anthonny works beautifully! This is turning out to be really useful. :+1:

**Comment by lai** [comment] 2015-02-26 20:15
I verified this is fixed. Please close this

**Comment by anthonny** [comment] 2015-02-26 20:29
😎

**Closed by anthonny** 2015-02-26 20:29 UTC
Labels: bug, should be fixed

**Comment by rajeevkannav** [comment] 2015-03-02 07:43
Index page shows only the last published post.

Its not working for me yet

**Comment by anthonny** [comment] 2015-03-02 08:15
Hi @rajeevkannav 
If you are using Firefox, you must update your repository from the upstream: 
https://www.youtube.com/watch?v=KCylB780zSM

**Comment by rajeevkannav** [comment] 2015-03-03 06:25
Done and that doesn't works :(

**Comment by rajeevkannav** [comment] 2015-03-21 03:07
@anthonny  I've updated my repository from the upstream. this issue still exists.

**Comment by rajeevkannav** [comment] 2015-03-21 04:03
![ScreenShot](http://i.imgur.com/ApWWbtd.png)

**Comment by anthonny** [comment] 2015-03-21 16:53
Could you add a screenshot of the posts page please?

**Comment by rajeevkannav** [comment] 2015-03-24 04:46
@anthonny 

Public Index Page ![ScreenShot](http://i.imgur.com/lzqdOoz.png)
Admin Index Page ![ScreenShot](http://i.imgur.com/D6QkEZy.png)
